application: vikash-kumar
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.png
  upload: static/img/favicon.png

- url: /robots.txt
  static_files: public/src/robots.txt
  upload: public/src/robots.txt

- url: /static
  static_dir: static

- url: /api/.*
  script: api_handler.app

- url: /.*
  script: router.app

libraries:
- name: jinja2
  version: "latest"

- name: webapp2
  version: "latest"
