application: vikash-kumar
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /bower_components
  static_dir: bower_components

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
