runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /(.*\.(gif|png))$
  static_files: public/build/favicons/\1
  expiration: "1s"
  upload: public/build/favicons/.*\.(gif|png)$
  secure: always

- url: /robots.txt
  static_files: public/build/robots.txt
  expiration: "1s"
  upload: public/build/robots.txt
  secure: always

- url: /favicon.ico
  static_files: public/build/favicons/favicon.ico
  expiration: "365d"
  upload: public/build/favicons/favicon.ico
  secure: always

- url: /manifest.json
  static_files: public/build/favicons/manifest.json
  expiration: "1s"
  upload: public/build/favicons/manifest.json
  secure: always

- url: /browserconfig.xml
  static_files: public/build/favicons/browserconfig.xml
  expiration: "1s"
  upload: public/build/favicons/browserconfig.xml
  secure: always

- url: /sitemap.xml
  static_files: public/build/sitemap.xml
  expiration: "1s"
  upload: public/build/sitemap.xml
  secure: always

- url: /images/(.*)
  static_files: public/build/images/\1
  expiration: "365d"
  upload: public/build/images/(.*)
  secure: always

- url: /sw.js
  static_files: public/build/scripts/sw.js
  expiration: "1s"
  upload: public/build/scripts/sw.js
  secure: always

- url: /scripts/(.*)
  static_files: public/build/scripts/\1
  expiration: "365d"
  upload: public/build/scripts/(.*)
  secure: always

- url: /stylesheets/(.*)
  static_files: public/build/stylesheets/\1
  expiration: "365d"
  upload: public/build/stylesheets/(.*)
  secure: always
  application_readable: true

- url: /LICENSE
  static_files: public/build/LICENSE
  expiration: "7d"
  mime_type: text/plain
  upload: public/build/LICENSE
  secure: always

- url: /api/.*
  script: api_handler.app

- url: /.*
  script: router.app

libraries:
- name: jinja2
  version: "latest"

- name: webapp2
  version: "latest"

skip_files:
- ^(.*/)?.*/src/.*$
- ^(.*/)?.*/temp/.*$
- ^(.*/)?.*/test/.*$
- ^(.*/)?.*/node_modules/.*$

- ^(src/.*)
- ^(temp/.*)
- ^(test/.*)
- ^(node_modules/.*)
